### PR TITLE
Extract file-copying duplication from tests

### PR DESCRIPTION
**Pull request by dennisschagt**

### CODE REVIEW

**Comment by dennisschagt** [comment]
Done, thanks for the review!

**Comment by Minoru** [comment]
There's a typo in the last commit, both in the body and the message: "acticle" instead of "article". Otherwise I'm ready to merge this.

**Comment by dennisschagt** [comment]
Oops, fixed

**Comment by Minoru** [comment]
Thank you for the work!

On a side note, please avoid force-pushing in the middle of a PR: GitHub doesn't show diffs between the old and new commit, and I have to re-review everything again. This wasn't a problem here, as the changes are small, but it would've been in a larger PR. You can pile up fixup commits and ask me to squash them before merging, or you can just make separate commits like you did for `CopyFile` -> `copy_file` rename. (Perhaps there are other solutions, but I'm not aware of them.)

**Comment by dennisschagt** [comment]
> On a side note, please avoid force-pushing in the middle of a PR

I wasn't aware this was a problem. Thanks for making me aware. I will try to keep this in mind.

**Comment by dennisschagt** [comment]
Just found out that `force-pushed` is clickable in messages like the following:
image

This links to a url in the format `<github-repo-url/compare/<old-commit-hash>..<new-commit-hash>`.
It looks like that doesn't work when there are multiple force-pushes without a review/comment in-between although manually navigating to the relevant compare url does work.

For example, the following url will show the diff between the commits before and after the two consecutive force pushes:
https://github.com/newsboat/newsboat/compare/e21b5f66045fcd346e0164413eb8f744a108aa1e..f3296c408c9bccbb0e679e0032c8de3809c39ef0


I'm still planning to not force-push during PRs anymore but the above might be useful if someone else uses a force-push.

**Comment by Minoru** [comment]
Wow, thanks a lot! This will definitely come in handy.

> It looks like that doesn't work when there are multiple force-pushes without a review/comment in-between

Yeah, I noticed this in my own PRs too: if I push multiple times in a row, GitHub simply combines everything into a single message. However, if a force-push introduces new commits, then the next force-push is going to be displayed separately—that's what happened when you renamed AssertArticleFileContent.

**Comment by Minoru** [comment]
> It looks like that doesn't work when there are multiple force-pushes without a review/comment in-between although manually navigating to the relevant compare url does work.

I see what you meant now: in https://github.com/newsboat/newsboat/pull/729 there were three force-pushes in a row, and GitHub only displays the last one. Bummer; I hoped this would work well enough for me to stop asking people not to force-push.

I can always dig up email notifications, but URLs there have to be re-written in the form you show above. Quite inconvenient.

**Pull request merged**
