### PR TITLE
Move feed reloading into a separate class

### PR DESCRIPTION
**Pull request by Minoru**
Submitting my changes as a PR to see if anyone is interested in reviewing my work. I will request reviews from a few more active contributors, but as with any request, feel free to decline ;) Reviews from others are welcome too!

The PR isn't terribly interesting or involved—just moving methods around. The only highlight is the first commit, where I do some code archeology.

The new class touches the `view`, so I didn't write any tests.

This work is done in relation to #213.

### CODE REVIEW

**Comment by kmws** [comment]
Looks good to me. Glad to see it moved out of controller. ;)

**Comment by Minoru** [comment]
Merged via 7b2c654a87e0ebfae52833252aabba534dcb9f4c. (Didn't want to confuse GitHub with a force-push of a rebase because that'd add 86 commits only 18 of which are related to this PR.)

Thanks for the reviews, everyone!

**Comment by noctux** [comment]
hmm, I'm sort of late to the party, but looks good to me.

Something we might want to consider in the future is the reload lock. Maybe finegrained locking on an per feed-basis as opposed to a global lock on the reloader might be nice (e.g.: slow feeds, I'm reloading four of them explicitly and selectively, and even though I have multiple reload threads the four reloads will happen sequentially because the reloader has a global lock).

**Comment by Minoru** [comment]
> slow feeds, I'm reloading four of them explicitly and selectively, and even though I have multiple reload threads the four reloads will happen sequentially because the reloader has a global lock

I'm not sure if you're talking about an imaginary situation where we introduced a global lock on `Reloader`, or our current situation with `Reloader::reload_mutex`. If the latter, the facts don't line up:
- `Reloader::reload_mutex` prevents us from running two "reload all" operations simultaneously. Individual reload threads (`reloadrangethread` objects) don't acquire it;
- selective reloading don't use threads—it calls `Reloader::reload()` right in the UI thread (#75). So you can't actually reload four feeds at once by pressing `r` on a few feeds.

I also don't see how it all relates to the GUID issue. That one is caused by Newsboat's incorrect assumption: database schema is written in such a way that an item always belongs to just one feed, and items are addressed by their GUIDs.

Am I completely misunderstanding your points there?

**Comment by noctux** [comment]
Ops, my bad. You are of course right. I made the wrong assumption that we might be able to call reload with two different index ranges at once at [downloadthread.cpp:31](https://github.com/newsboat/newsboat/pull/253/files#diff-d12bf59eecf05f57e846ec2a6efeea26R31) which is of course moot, as like you pointed out, both code path actually happen to be triggered by the UI thread in the foreground. I'm sorry.

The other comment was concerning updating (and thereby also writing feeds to the database) in parallel. Currently, as far as I understand, there is locking in place (using mtx, residing in view.h, which looks a bit odd) to serialize the database-transactions (e.g. in cache::externalize_rss). In theory, as long as the guids were guaranteed to be distinct, some of those operation could be performed in parallel. however, as we cannot currently guarantee that, we can't really update feeds in parallel anyways... therefore putting too much effort in there wouldn't see a payoff there in the forseeable future.

**Comment by Minoru** [comment]
Ah, got it. I never thought about parallelizing DB accesses, but I think we'll get there eventually.

**Pull request closed without merging**
