### PR TITLE
add const to dump_config fix #1234

### LINKED ISSUE #1234: Constify ConfigActionHandler::dump_config
(The method `ConfigActionHandler::dump_config`](https://github.com/newsboat/newsboat/blob/e4f28127f6126a82bc2bd5a3025c46858b4af9d1/include/configactionhandler.h#L15) writes the handler's configuration into a vector of strings. It's obvious that this method *shouldn't* modify its object, so we should mark it `const`. However, this requires updating all the implementers of this method, which is a bit of work.

It appears that this issue is mostly about replacing `std::map::operator[]` with `std::map::find()` (because the former doesn't work on `const` maps). Thus, this should be doable even for someone who has no idea about Newsboat's internals.

If you would like to work on this, please comment! And don't hesitate to ask questions if you get stuck.

### PR DESCRIPTION
**Pull request by davbrito**
fixes #1234

### CODE REVIEW

**Comment by Minoru** [comment]
:wave: Looks like you didn't set up a build environment locally? It might take a long white to get this building if you're only using CI. Feel free to mark this PR as a draft for now ("Convert to draft" in the sidebar on the right), and convert it back when it's ready for review. It'd probably be wise to squash the commits before the review, but I can do that while merging as well.

**Comment by davbrito** [comment]
@Minoru It is now ready for review.

**Review by Minoru — APPROVED** [review]
Excellent, thanks a lot! :+1:

**Comment by Minoru** [comment]
If you'd like to work on some more Newsboat issues, check out [the "refactoring" label](https://github.com/newsboat/newsboat/labels/refactoring) — it got plenty of stuff which mostly requires changing things without breaking them :) There's also "bug" label, but working on those usually requires learning how to use Newsboat. And of course, all the other issues on the tracker are up for grabs, so if you feel compelled to work on any of them — just comment and I'll assign it to you.

Thanks once again for the pull request!

**Comment by davbrito** [comment]
> If you'd like to work on some more Newsboat issues, check out [the "refactoring" label](https://github.com/newsboat/newsboat/labels/refactoring) — it got plenty of stuff which mostly requires changing things without breaking them :) There's also "bug" label, but working on those usually requires learning how to use Newsboat. And of course, all the other issues on the tracker are up for grabs, so if you feel compelled to work on any of them — just comment and I'll assign it to you.
> 
> Thanks once again for the pull request!

That sounds good for me. Thanks for the suggestion. I'll take a look to it.

**Comment by davbrito** [comment]
Hello @Minoru 
Can you add the hacktoberfest-accepted label to this please?

**Comment by Minoru** [comment]
Sure, done! Why is it needed, though? According to [the rules](https://hacktoberfest.digitalocean.com/details#rules), this PR definitely counts since it's already merged.

**Comment by Minoru** [comment]
Ah, I opened my own Hacktoberfest dashboard now and see that some of my Newsboat PRs weren't counted either. Looks like I removed the "Hacktoberfest" topic from the repo too soon (I did it in the evening on November 1st, after the end of Hacktoberfest). I added the topic back, let's see if Hacktoberfest site picks that up.

**Comment by davbrito** [comment]
> Looks like I removed the "Hacktoberfest" topic from the repo too soon (I did it in the evening on November 1st, after the end of Hacktoberfest)

Yes. In my dashboard this or was marked as ineligible because the repository was not participating. Let's see what does it says now.

**Comment by Minoru** [comment]
@davbrito So what does it say?

**Comment by davbrito** [comment]
@Minoru it still says ineligible :'c

Screenshot_20201104-154751-1

**Comment by Minoru** [comment]
I wrote an email to hacktoberfest@digitalocean.com. Let's see if they can resolve (or at least explain) this.

**Comment by Minoru** [comment]
Got a response explaining that they're aware of the issue, but for now, this is the intended behaviour: by deleting the topic, I un-accepted all the PRs still in the review period (which is two weeks after the PR becoming ready for review), and re-accepting them after October 31st does nothing.

Sorry @davbrito, I should've waited a few more weeks before removing that topic :( I see you made 7 PRs in October, two of which aren't merged yet and this one is not counted — are the remaining 4 counted all right? Will you get your prize after all?

**Comment by davbrito** [comment]
It's okay. It will be for the next then :'c

I made 7 PRs. Of which are:
- Accepted ✔️: 1
- Ineligible repository ❗: 2 (Counting this one)
- In review ⌚: 2
- Pending ❔: 2

**Comment by davbrito** [comment]
@Minoru Anyway thanks for everything. You've been very kind. 😊

**Pull request merged**
