### PR TITLE
Add DecSync support (with shared library)

### PR DESCRIPTION
**Pull request by 39aldo39**
I have finally implemented a multiplatform library for DecSync (see [libdecsync](https://github.com/39aldo39/libdecsync)), which also creates a shared library that is usable from C/C++.

This pull requests adds support for DecSync using this shared library, see also #381.

There are still two modifications in the RemoteApi required as discussed in #462: the `mark_*_read` functions need objects instead of identifiers.

### CODE REVIEW

**Comment by Minoru** [comment]
Whoa! That's a lot of work; thank you! I skimmed it, and it seems alright. Need to compile it locally and try it out.

libdecsync is GPL, though, which is incompatible with MIT. Can libdecsync be re-licensed under LGPL, to permit dynamic linking with non-GPL code like Newsboat?

**Comment by Minoru** [comment]
Ah, wait, it's under *Library* GPL. Never even heard of it before! Looks like it's superseded by Lesser GPL, though; any reason to use an older license?

**Comment by 39aldo39** [comment]
There are currently 3 LGPL licenses (see https://opensource.org/licenses/lgpl-license), but they renamed it from Library to Lesser in v2.1.

I did include the old version as [Evolution Data Server](https://gitlab.gnome.org/GNOME/evolution-data-server) uses it, and I take code from it in Evolution-DecSync. It doesn't specify any version in the headers, so any version is allowed. I just did the same, as it is the most compatible. But I found it a bit confusing as well, I might make it clearer.

**Comment by Minoru** [comment]
After sleeping on this, I don't think it's the right time to introduce this after all. Sorry to change my stance so late in the process, but adding yet another dependency, which isn't yet available in any distro, conflicts with my goal of moving Newsboat to Rust—I already got downstream maintainers busy with packaging Rust crates, it's better not to add to the burden. I personally don't want to deal with adding this to CI and Snap, too.

This PR does half the work already, though, so I'll add a note to #381 and will start from here when I decide to continue with this.

Once again, sorry for the sudden change of heart, but it simply doesn't sit right with me.

**Pull request closed without merging**
