### PR TITLE
Explain "*" pattern in `ignore-article` better

### PR DESCRIPTION
**Pull request by Minoru**
In relation to #193. @decibyte, what do you think about new wording?

### CODE REVIEW

**Comment by decibyte** [comment]
I think it's a better way of saying the same, but it's still not spelled out for feature optimists like me that it *cannot* be used as a wildcard in URLs :)

**Comment by Minoru** [comment]
Okay :) I made it even more explicit. How do you feel about the updated wording?

**Comment by decibyte** [comment]
I feel taken very good care of now. Thanks!

**Comment by Minoru** [comment]
Cool! Thank you for the review.

**Pull request merged**
