### PR TITLE
Add support for sorting feedlist on recent updates

### PR DESCRIPTION
**Pull request by TwilightSpectre**
I subscribe to many feeds, of which some update infrequently or stop
posting entirely. Occasionally I like to remove those feeds that haven't
updated in considerable time, and in general I would like to be able to
sort the feeds in order of how long since they have updated.

Here I've added a new option for the `sort` and `revsort` keycommands:
`recent`, bound to the `r` key. This sorts the feeds based on the most
recent item in the feed, with a normal sort having the most recent
publication dates at the top of the list. 

A couple of questions in regard to this: do you think this is a
worthwhile feature that other normal users might find helpful/useful, or
is it feature bloat? Also, is there somewhere that I should add this to
the documentation? The best I could find was to change the description
of the `feed-sort-order` config command (`doc/configcommands.dsv L27`)
to more closely match the formatting of the `article-sort-order`
command, and add this option there.

### CODE REVIEW

**Comment by Minoru** [comment]
Thank you for the pull request! I'm happy with the code, but I suggest renaming the option to "recency", because it simply sounds more correct: "sort by recency" vs. "sort by recent". But I'm not a native speaker; you tell me :)

> do you think this is a feature that other normal users might find helpful/useful

Absolutely! It's a good addition to an existing "date" sorting for articles.

> Also, is there somewhere that I should add this to documentation? The best I could find was to change the description the feed-sort-order config command (doc/configcommands.dsv L27) to more closely match the formatting of the article-sort-order command, and add this option there.

That's the only place, everything is generated from there.

**Comment by TwilightSpectre** [comment]
Yes, `recency` probably does fit better than `recent`. Originally I
was aiming for 'most recent', but didn't want to extend the line
length too much longer than it already was.

**Comment by tsipinakis** [comment]
> I suggest renaming the option to "recency", because it simply sounds more correct

Just pitching in a bit: Both of these sound weird to me and would confuse me at first glance. I'd propose "last updated"

"Sort by last updated" sounds way better IMO.

**Comment by Minoru** [comment]
"Last updated" is fine by me. I also asked on IRC, and got two responses, one neutral and one in slight favour of "last updated". Let's go with that one, then.

It'd be a bit rude of me to ask @TwilightSpectre to change the PR *again*, so I'll do the changes myself and then merge it.

**Comment by Minoru** [comment]
Done! Thank you very much, @TwilightSpectre, and @tsipinakis too!

**Pull request merged**
