### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by Tonus1**
Getting rid of the 3 last fuzzy strings

### CODE REVIEW

**Review by der-lyse — APPROVED** [review]
Consider my French as pretty much non-existent. However, from a punctuation point of view it's looking good to me.

Is there a subtle difference between "non lus" and "à lire" that should be kept or would it make sense to consistently go for one of them in all cases?

**Review by Minoru — APPROVED** [review]
Thanks! This looks good to me too.

@der-lyse, please merge once you've discussed the wording. (I'm not merging it myself now because you might decide to change it somehow.)

**Comment by Tonus1** [comment]
You're right, let's keep "non lus".

I'm still not very good at choosing between beeing conservative or not for existing translation, sorry.

**Comment by der-lyse** [comment]
Alright, do you want to do that in this MR or change it in a separate one, @Tonus1?

No worries, we all know translation is hard. :-)

**Comment by Tonus1** [comment]
I'm quite noob with github. Already missed last release... I would be glad that these changes would me merged as soon as it could be.

**Pull request merged**
