### PR TITLE
Pr#914 fslock

### PR DESCRIPTION
**Pull request by chux0519**
related PR: https://github.com/newsboat/newsboat/pull/914

Hi, I did a work around to fix the `CARGO_BIN_EXE_xxx` error in Rust < 1.43

### CODE REVIEW

**Comment by chux0519** [comment]
Basicly, added a function to get the `lock-process` dir

```rust
+fn get_exe_dir(exe: &str) -> Result<PathBuf, Error> {
+    let mut target_dir = env::current_exe().expect("exe path");
+    while target_dir.pop() {
+        if target_dir.join(exe).exists() {
+            return Ok(target_dir.join(exe));
+        }
+    }
+    Err(Error::new(ErrorKind::NotFound, exe))
+}
```

then use this when `CARGO_BIN_EXE_xxx` is not available

```rust
-    let mut child = Command::new(env!("CARGO_BIN_EXE_lock-process"))
+    let target_dir = match env::var("CARGO_BIN_EXE_lock-process") {
+        Ok(dir) => dir,
+        Err(_) => get_exe_dir("lock-process")
+            .unwrap()
+            .to_str()
+            .unwrap()
+            .to_string(),
+    };
+
+    let mut child = Command::new(target_dir)
...
```

Tested using 1.40.0-x86_64-unknown-linux-gnu

**Comment by chux0519** [comment]
> Looks good! Can you please rebase onto current `master` branch? We've added more checks to CI, and I'd like to see them pass.

Sure, I will force update this branch after rebasing

**Comment by chux0519** [comment]
Hit clippy error, I will fix this

**Comment by Minoru** [comment]
[The Travis build](https://travis-ci.com/github/newsboat/newsboat/builds/174902719) has finished, but GitHub still says it's in progress. Oh well. Merging.

Thanks for the PR, @chux0519!

**Comment by pickfire** [comment]
@chux0519 Nice, I didn't think of this.

**Pull request merged**
