### PR TITLE
Port TagSoupPullParser to Rust

### PR DESCRIPTION
**Pull request by dennisschagt**
Written half a year ago, delayed because there were some open PRs chagning the TagSoupPullParser; and then forgot about it.

I guess it would be useful to add some tests on the Rust side as well.
- [ ] Add tests in Rust
- [ ] Check if code can be made a little bit more readable (related: get rid of `// TODO: Cleanup`)

I probably won't work on this until after the new 2.29 release.
Just opening this PR now so I won't forget about these changes again.

### CODE REVIEW

**Comment by juntuu** [comment]
Hi, I happened to also port the parser few weeks back (just for fun, I was bored).

I ported the tests from c++ as well, which also work with your code (as I'd expect) with only minor type differences. Feel free to grab those from https://github.com/juntuu/newsboat/tree/tagsoup-tests.

And for the second point, not sure if I did anything "cleaner", but you can take a look for inspiration. The code is here: https://github.com/juntuu/newsboat/tree/rust-port.

**Comment by dennisschagt** [comment]
@juntuu: Nice, I don't have time for a detailed look at the moment, but from a quick glance it looks good.
Especially nice to see that you ported the HtmlRenderer already.

Feel free to open a PR for your changes.
I'm completely fine with abandoning my own PR if your changes look good overall.

**Comment by Minoru** [comment]
Sorry, I'm not looking to port any more code to Rust until #1437 and related issues are resolved, because more Rust code means more opportunities for encoding-induced panics. Let's keep this PR on a back burner for now, and return to it once we can guarantee that Rust will only see UTF-8 inputs.

**Comment by dennisschagt** [comment]
Closing this PR as it only contains a subset of the porting-to-rust done in https://github.com/newsboat/newsboat/pull/2188

**Pull request closed without merging**
