### PR TITLE
Document `article-sort-order` default and explain it better

### LINKED ISSUE #1560: Default for 'article-sort-order' is actually 'date-asc' (yet sorts in descending order anyway)
I was trying to figure out how to set the default ordering of articles to ascending by date (just to try it out, since in that order 'n' moves forward in time). I tried `article-sort-order "date-asc"` as implied by the man page, but this didn't work.

> article-sort-order (parameters: <sortfield>[-<direction>]; default value: date)
> The <sortfield> specifies which article property shall be used for sorting, currently available are: `date`, `title`, `flags`, `author`, `link`, `guid` and `random`. The optional <direction> specifies the sort direction. `asc` specifies ascending sorting, `desc` specifies descending sorting. Note that direction does not affect `random` sort order. For `date`, `desc` is default, for all others, `asc` is default.

In fact, the code gives "date-asc" as the default, and in practice both "date" and "date-desc" reverses the order to ascending.

```
// src/configcontainer.cpp line 26-28
	{
		"article-sort-order",
		ConfigData("date-asc", ConfigDataType::STR)},
```

**Newsboat version**:

```
newsboat r2.23-22-g3bdab - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat r2.23-22-g3bdab
System: Linux 5.10.23-1-MANJARO (x86_64)
Compiler: g++ 10.2.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.75.0 OpenSSL/1.1.1j zlib/1.2.11 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 (compiled with 7.75.0)
SQLite: 3.35.1 (compiled with 3.35.1)
libxml2: compiled with 2.9.10
```

Config file:

```
article-sort-order "date-asc"
```

This is very minor and I don't know if you even want to bother fixing it, but I thought I'd best mention it.

### PR DESCRIPTION
**Pull request by Minoru**
ce2e53a80f186b521fb6c4096a74ea5869826d24 introduced an
`article-sort-order` setting, adding ways to sort by fields other than
the date. For unspecified reason, the default order for the new fields
was different from the date field: "date" meant descending order (newest
first), while other fields used ascending order by default (for strings
that meant lexicographic: a, b, c, d, e...). The issue which that commit
fixed, https://code.google.com/archive/p/newsbeuter/issues/40, doesn't
explain this oddity in defaults.

ad5c5ea049f39c814840bd4fad197e473b12e1dc documented the new setting.

It's worth noting that the "date" sorting was done in SQL upon loading
the feed, whereas all other sorts were implemented in C++. This worked
at the time because the setting was fixed in the config, and there was
no way to change it at runtime.

64b6fc1f838f8a600b438313eee167b9f6e6ea3f allowed to change the setting
at runtime using g and G keys. By necessity, the "date" sorting was
moved from SQL to C++. This introduced an interesting bug: the
comparison function for dates was implemented such that it sorted in
ascending order by default. That was different from what SQL was doing,
but Newsboat's sorting function wasn't adjusted to match. As a result,
sorting by "date-desc" resulted in ascending sort, where oldest items
came first.

Instead of addressing this change by fixing the sorting function, that
commit changed the meaning of "-desc" and "-asc" for "date", and changed
the default for `article-sort-order`. The new default, "date-asc", meant
descending order (newest first), while "date-desc" meant ascending order
(oldest first).

This counter-intuitive behaviour survives to this day in Newsboat.
I think it's too late to change now, since it'll break configurations
that set `article-sort-order` to "date", "date-asc", or "date-desc".
Instead, this commit improves docs somewhat, and promises to fix this
inconsistency in some future major version of Newsboat.

Fixes #1560.

### CODE REVIEW

**Comment by Minoru** [comment]
@PetraOleum, you filed #1560, so please take a look — does this PR improves the situation at all?

**Comment by Minoru** [comment]
I filed https://github.com/newsboat/newsboat/issues/1566 for specific steps to fix this in some future major release.

**Review by der-lyse — APPROVED** [review]
Sounds good! And nice writeup.

**Comment by PetraOleum** [comment]
That looks like the best that could be done without actually making a breaking change.

**Comment by Minoru** [comment]
Thanks to both of you for taking the look! Merging ^_^

**Pull request merged**
