### PR TITLE
implement feedly integration 

### PR DESCRIPTION
**Pull request by SeanBE**
I would love some feedback on this. There are probably better ways of doing X and Y. I've left a few TODOs which I want to revisit first as well. 

I've gone down the route of users passing in their own developer tokens (30 day expiry). If you pay for pro, you can use the API (instead of the web console) to get a new access token. We don't need to implement oauth or run into #949 (rate limits are 250 a day for free users / 500 for paid).

A few bullet points:
- I've implemented fetching urls by only grabbing those with unread counts ( I have lots of feeds and I want to avoid hitting the rate limit) 
- I've not implemented marking individual items yet.
- I need to go through the style guide once more. I've ran code through astyle.

### CODE REVIEW

**Comment by Minoru** [comment]
Thanks for looking into Feedly! Easily the most-requested feature in Newsboat *and* Newsbeuter.

500 calls/day is a draconian limit. Between feed updates and mark-as-read calls, this won't be enough for anything but testing ([which is Feedly's intent](https://developer.feedly.com/v3/developer/)). @SeanBE, the commit message on https://github.com/newsboat/newsboat/pull/961/commits/6f63801ced6f6fa8e06a097e16848b8b90d4b361 gives me hope that you've worked with OAuth in Rust. Is it so? I wonder if it's better to spend time implementing OAuth than working around dev token limitations.

I skimmed the code, but I'll hold off a review until we decide if this is the approach we're going to take. But I'll comment on https://github.com/newsboat/newsboat/pull/961/commits/0dad45a35a5e11b1afd866fda36c8c21a34862bf: it does make the code simpler, but it also marks every item unread, always. In other words, it introduces a bug :) To really simplify that method, you'll have to create a set of known labels ("fresh", "kept-unread" etc.) and see if it intersects with `item.labels`. That'd require some fiddling with C++ iterators (I think), so I'm ok with you just dropping that commit in the future.

**Comment by SeanBE** [comment]
Re: 0dad45a, I don't know what I was thinking when i made that change :) I'll drop it. 

I've emailed Feedly if we would be able to get a client id and secret for their live environment. I'll let you know when I hear back from them).

**Comment by Minoru** [comment]
Wouldn't [sandbox](https://developer.feedly.com/v3/sandbox/) be sufficient for now? (Sorry if the question is dumb, I don't have any experience with OAuth and I haven't even read Feedly's docs)

**Comment by Minoru** [comment]
Oh, I guess you requested a live client id as they describe [here](https://groups.google.com/forum/#!topic/feedly-cloud/T-fDw6ZiDL8).

**Comment by SeanBE** [comment]
We're going to be using the sandbox for building/testing the oauth implementation. They recommend asking before any development just in case they reject our request for production credentials.

**Comment by Minoru** [comment]
Feedly's terms of service are a little worrying:

> D.1 Application are not allowed to mass import or export information from the feedly cloud without explicit permission.

I guess the *spirit* of this is "don't overload Feedly's systems", but it won't hurt to explain that Newsboat fetches all feeds on a schedule, in quick succession, possibly in parallel. It sends `If-Modified-Since` HTTP header, so it shouldn't create undue load. Does that still count as "mass export"?

> D.2 The platform will evolve to include search and alerts. There will be sponsorship/monetization associated with these features. Applications agree to not compete with these features and do the best effort to integrate these features into the user experience to help support operating cost of the platform. In the case of search, the application is committing to display search results in the order delivered by the infrastructure and without removing sponsored and featured results.

Newsboat already contains search, but it only works on what's in Newsboat's local database, which is limited to "recent history" (i.e. items that were fetched *after* the user integrated Newsboat with their Feedly account). Does Feedly consider this as competition?

We aren't clear what "alerts" are, so we can't know if Newsboat has anything similar.

> D.4 We currently do not enforce usage quota. Developers will try keep the platform healthy by minimizing traffic and load when possible. An acceptable rate would be 3 unread count requests per user per hour and 60 streams requests per user per hour and 20 search requests per user per hour. If an application needs more than that, please contact feedly to review the use case together.

@SeanBE, I'll have to read up on their API, but that sounds like it requires us to synchronize in two steps:

1. check which feeds have unread items;
2. fetch just those feeds.

That doesn't work for Newsboat. Some of Newsboat's features can't be implemented this way. We already ran into that with Inoreader. Newsboat's model is "fetch everything, shove it into a database, provide services from that".

What I'd ask Feedly: keeping in mind that Newsboat sends `If-Modified-Since` header, is it okay if it makes one request per feed, as often as once per minute? (We can discuss limits, e.g. prevent Newsboat users from checking Feedly faster than once per hour). The number of requests will still scale with the number of user's feeds, there's no way around that, so 60 req/h isn't nearly enough.

**Comment by Minoru** [comment]
Two more things:

1. assuming we do get a client id, I'd like it to be tied to the project somehow, or at least to me. You've been around the project a while, but I've been around longer, and I'd prefer to make sure that even if you disappear, I still can cancel or service the token.

2. feel free to CC me in discussions with Feedly. My email is in my GitHub profile.

**Comment by Minoru** [comment]
For the record: we got a response today. Feedly devs find Newsboat "an interesting project", but wonder how we're going to keep OAuth secrets safe. Since Newsboat is open-source, anyone can copy our keys and impersonate Newsboat. If impersonators misbehave, keys will be retracted, rendering Feedly integration in Newsboat unusable.

There seem to be [two possible solutions](https://softwareengineering.stackexchange.com/questions/99295/how-do-i-store-the-oauth-v1-consumer-key-and-secret-for-an-open-source-desktop-t):

1) keep secrets on a server somewhere and proxy requests through it. This requires a somewhat intelligent proxy, some abuse control (rate-limiting, banning overly active IPs), and obviously requires maintenance. It sounds like something that should've been implemented already, but I couldn't quickly find any such implementations.

2) require users to obtain their own keys from Feedly. This isn't very user-friendly, since the process is done via email.

The second option sounds like a good start, so I decided to go with that. @SeanBE is going to respond to Feedly and we'll see if they're okay with this approach.

**Comment by Minoru** [comment]
Given [my summary of the situation](https://github.com/newsboat/newsboat/issues/61#issuecomment-638184808), there is no point keeping this open. Sorry it didn't make it into master, @SeanBE!

**Pull request closed without merging**
