### PR TITLE
ItemList: make delete-all-articles affect only visible items

### LINKED ISSUE #1360: ignore-mode "display" makes possible to delete invisible articles
```
newsboat 2.21.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.21.0
System: Linux 5.9.12-1-default (i686)
Compiler: g++ 10.2.1 20200825 [revision c0746a1beb1ba073c7981eb09f55b3d993b32e5c]
ncurses: ncurses 6.2.20201031 (compiled with 6.2)
libcurl: libcurl/7.73.0 OpenSSL/1.1.1h-fips zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.41.0 (compiled with 7.73.0)
SQLite: 3.34.0 (compiled with 3.33.0)
libxml2: compiled with 2.9.10
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
*read below
```

Steps to reproduce the issue:

0. Have some articles in a feed with certain url containing some 'keyword' in content body

1. In config set
```
ignore-mode "display"
ignore-article "the url of the feed" "content !~ keyword"
```

2. Run newsboat and open the feed (the killfile works fine)
4. Press CTRL+D to delete all articles visible in the feed
5. Exit newsboat
6. Remove the 'ignore-article' line
7. Run newsboat again and go to the same feed

### Expected:

The articles containing 'keyword' should remain. IOW only the ones *displayed* in step 2 should have been deleted.

### Actual:

All articles in the feed are deleted.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #1360.

Reviews are welcome. Will merge in three days.

### CODE REVIEW

**Review by dennisschagt — APPROVED** [review]
Looks correct, LGTM.

It might be useful to update the description of `delete-all-articles` in `src/keymap.cpp`.

I suspect there might be an issue similar to https://github.com/newsboat/newsboat/issues/1360 but with invisible (ignored) items being marked as read (when using `mark-feed-read` operation).
(I did not try to reproduce it yet and I'm not sure it would be an actual issue).

**Comment by Minoru** [comment]
> It might be useful to update the description of delete-all-articles in src/keymap.cpp.

Makes sense! Please see https://github.com/newsboat/newsboat/pull/1387/commits/b8940921242c04808553bbc05322c1293c17c44e for my attempt at it.

> I suspect there might be an issue similar to #1360 but with invisible (ignored) items being marked as read (when using mark-feed-read operation).

Oh right, I meant to file another "Audit for bugs similar to" issue, but forgot. Will do so now. Thanks!

**Comment by dennisschagt** [comment]
> > It might be useful to update the description of delete-all-articles in src/keymap.cpp.
> 
> Makes sense! Please see [b894092](https://github.com/newsboat/newsboat/commit/b8940921242c04808553bbc05322c1293c17c44e) for my attempt at it.

Looks good, thanks!

**Comment by Minoru** [comment]
Cool, I'll merge this then!

**Pull request merged**
