### PR TITLE
Updated last translator field and comment

### PR DESCRIPTION
**Pull request by maxigaz**
This is a follow-up to the discussion about #1935.

### CODE REVIEW

**Comment by Minoru** [comment]
i18nspector won't have it: https://cirrus-ci.com/task/5306342406619136?logs=main#L3 Please restore the header to how it was in #1935; I'll still credit you in the changelog (because I look at Git history rather than file contents when I update changelog).

**Comment by maxigaz** [comment]
> Please restore the header to how it was in #1935

Do you mean changing it to how it was before the commit e5d1c6a275bae68958a131b3054f52f590720288? If not, could you be more specific?

> I'll still credit you in the changelog (because I look at Git history rather than file contents when I update changelog).

OK.

**Comment by Minoru** [comment]
> Do you mean changing it to how it was before the commit e5d1c6a? If not, could you be more specific?

Yeah, I mean just that; sorry, I should have just pointed at the commit instead of being all vague.

**Comment by maxigaz** [comment]
I've just reverted that commit and then updated the date of the last revision. Let me know if this is OK or if you want me to change anything else. Thank you!

**Comment by Minoru** [comment]
No, this is perfect, thanks!

**Pull request merged**
