### PR TITLE
optimize RssIgnores::matches function

### PR DESCRIPTION
**Pull request by danieloh0714**
Optimize the `RssIgnores::matches` function by changing the underlying data structure that stores `ignore-article` commands from a `std::vector` to a `std::unordered_multimap`.

Only the keys for the `RssItem` feed url as well as `*` could be looked up; if none of those were present as keys in the map, then the map still has to be iterated through in order to do [feed url RegEx checking](https://github.com/newsboat/newsboat/blob/b448e5bf202d6c5656c123d2faf3c43de117c1a5/src/rssignores.cpp#L118-L123).

Part of https://github.com/newsboat/newsboat/issues/345.

### CODE REVIEW

**Comment by danieloh0714** [comment]
To really optimize this method, I think a prefix tree would be the best solution. That way we can do one pass through the prefix tree and do the proper checks for `*`, the exact feed url, and all the RegEx branches of the tree. What do you think, @Minoru ?

**Comment by Minoru** [comment]
Thanks! The code looks good, but I'm yet to do the benchmarks.

I had another idea in #345, what do you think of it?

> we can get feed's URL once, lookup the associated ignore-article rules, and use that "shortlist" when checking individual items

That change is more invasive though, so might be worth a separate PR.

> To really optimize this method, I think a prefix tree would be the best solution.

I think it will only be faster if we have a lot of rules which are **not** regex rules (i.e. don't start with `REGEX_PREFIX`). In that case, a prefix tree will greatly reduce the number of iterations we do to process the regex rules. But thanks to your changes, we can achieve the same speedup by simply putting regex rules into a separate map.

**Comment by danieloh0714** [comment]
> we can get feed's URL once, lookup the associated ignore-article rules, and use that "shortlist" when checking individual items

To be honest, I was a little confused on what you meant by this (still new to the codebase). I'd be happy to look into it in a separate PR if you would be willing to elaborate on it a bit more.

> we can achieve the same speedup by simply putting regex rules into a separate map

Ahhh, good point. I can go ahead and make that change as part of this PR.

**Comment by danieloh0714** [comment]
Alright, I separated the RegEx and non-RegEx `ignore-article` rules into separate data structures. The non-RegEx rules are in a `std::unordered_multi_map` to allow quick lookup of either `*` or the `RssItem`'s feed url. The RegEx rules are in a `std::vector` as we still have to iterate through them and check if each pattern matches the `RssItem`'s feed url. Let me know what you think, @Minoru .

**Comment by Minoru** [comment]
I agree that `vector` is the appropriate data structure for regex rules. The code looks good, but I still haven't ran the benchmarks :)

I'll elaborate on the other idea in the issue itself.

**Comment by Minoru** [comment]
Benchmarking results aren't spectacular enough to be graphed, but I'll include the raw numbers below. Frankly, I'd merge this code even if benchmarks showed zero difference, because I like the improvements to clarity. Thanks for the work, @danieloh0714!

<details> 
  <summary>Results for r2.34-175-g501a (master branch)</summary>

```
$ for i in `seq 0 20` ; do echo $i ; for i in `seq 3` ; do echo q | time ./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >/dev/null 2>&1 ; done ; done
0
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.36s user 7.38s system 99% cpu 29.770 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.14s user 7.21s system 99% cpu 30.377 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.79s user 7.23s system 99% cpu 31.054 total
1
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.57s user 7.12s system 99% cpu 30.726 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.20s user 7.05s system 99% cpu 30.272 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.84s user 7.18s system 99% cpu 31.049 total
2
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.48s user 7.37s system 99% cpu 29.864 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.92s user 7.04s system 99% cpu 29.983 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.28s user 7.18s system 99% cpu 30.470 total
3
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.82s user 7.05s system 99% cpu 29.899 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.97s user 7.29s system 99% cpu 30.280 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.42s user 7.02s system 99% cpu 30.467 total
4
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.74s user 7.16s system 99% cpu 29.906 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.40s user 7.06s system 99% cpu 30.487 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.59s user 7.01s system 99% cpu 30.626 total
5
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.70s user 7.20s system 99% cpu 29.922 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.03s user 7.06s system 99% cpu 30.114 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.08s user 7.34s system 99% cpu 30.449 total
6
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.55s user 7.00s system 99% cpu 29.588 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.19s user 7.19s system 99% cpu 30.389 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.26s user 7.09s system 99% cpu 30.362 total
7
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.75s user 7.11s system 99% cpu 29.889 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.10s user 7.09s system 99% cpu 30.208 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.15s user 7.29s system 99% cpu 30.456 total
8
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.28s user 6.75s system 99% cpu 30.048 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.13s user 7.08s system 99% cpu 30.217 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.11s user 7.29s system 99% cpu 30.412 total
9
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.65s user 7.10s system 99% cpu 29.768 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.35s user 7.33s system 99% cpu 30.706 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.31s user 7.32s system 99% cpu 30.653 total
10
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.51s user 7.21s system 99% cpu 29.744 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.25s user 7.14s system 99% cpu 30.420 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.48s user 6.91s system 99% cpu 30.403 total
11
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.84s user 7.04s system 99% cpu 29.903 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.02s user 7.24s system 99% cpu 30.283 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.05s user 7.17s system 99% cpu 30.231 total
12
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.87s user 6.94s system 99% cpu 29.834 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.76s user 7.25s system 99% cpu 30.033 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.60s user 7.05s system 99% cpu 30.686 total
13
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.11s user 6.80s system 99% cpu 29.921 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.59s user 7.15s system 99% cpu 30.766 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.03s user 7.30s system 99% cpu 30.340 total
14
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.90s user 7.20s system 99% cpu 30.138 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.02s user 7.31s system 99% cpu 30.351 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.16s user 7.15s system 99% cpu 30.327 total
15
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.25s user 6.92s system 99% cpu 30.200 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.43s user 7.05s system 99% cpu 30.484 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.51s user 7.24s system 99% cpu 30.766 total
16
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.88s user 7.07s system 99% cpu 29.968 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.42s user 7.13s system 99% cpu 30.576 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.51s user 7.03s system 99% cpu 30.555 total
17
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.73s user 7.38s system 99% cpu 30.128 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.94s user 7.14s system 99% cpu 30.096 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.77s user 7.47s system 99% cpu 30.279 total
18
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.69s user 7.03s system 99% cpu 29.749 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.16s user 7.34s system 99% cpu 30.535 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.49s user 7.33s system 99% cpu 30.848 total
19
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.12s user 7.06s system 99% cpu 30.190 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.49s user 7.07s system 99% cpu 30.572 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.26s user 7.08s system 99% cpu 30.349 total
20
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.86s user 7.07s system 99% cpu 29.942 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.27s user 7.23s system 99% cpu 30.508 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  23.81s user 7.12s system 99% cpu 30.948 total
```

</details>

<details>
<summary>Results for r2.34-158-g2472 (this PR)</summary>

```
$ for i in `seq 0 20` ; do echo $i ; for i in `seq 3` ; do echo q | time ./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >/dev/null 2>&1 ; done ; done
0
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.43s user 6.94s system 99% cpu 29.374 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.48s user 7.10s system 99% cpu 29.585 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.35s user 7.13s system 99% cpu 29.488 total
1
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.20s user 7.18s system 99% cpu 29.382 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  21.98s user 7.30s system 99% cpu 29.281 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.98s user 6.91s system 99% cpu 29.892 total
2
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.19s user 7.09s system 99% cpu 29.282 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.05s user 7.06s system 99% cpu 29.122 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.32s user 7.08s system 99% cpu 29.409 total
3
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.50s user 7.04s system 99% cpu 29.547 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.04s user 7.33s system 99% cpu 29.379 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.40s user 7.05s system 99% cpu 29.450 total
4
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.56s user 6.95s system 99% cpu 29.517 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.94s user 7.15s system 99% cpu 30.092 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.41s user 7.10s system 99% cpu 29.511 total
5
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.57s user 7.04s system 99% cpu 29.613 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.49s user 6.84s system 99% cpu 29.340 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.14s user 7.11s system 99% cpu 29.261 total
6
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.14s user 7.21s system 99% cpu 29.356 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.18s user 7.11s system 99% cpu 29.291 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.15s user 7.16s system 99% cpu 29.304 total
7
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.23s user 7.08s system 99% cpu 29.320 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.17s user 7.11s system 99% cpu 29.289 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.42s user 7.24s system 99% cpu 29.668 total
8
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.10s user 7.00s system 99% cpu 29.102 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.09s user 7.15s system 99% cpu 29.241 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  21.89s user 7.20s system 99% cpu 29.097 total
9
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.54s user 6.97s system 99% cpu 29.512 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  21.99s user 7.50s system 99% cpu 29.495 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.05s user 7.29s system 99% cpu 29.348 total
10
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.35s user 7.03s system 99% cpu 29.389 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.16s user 7.23s system 99% cpu 29.400 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.34s user 6.96s system 99% cpu 29.307 total
11
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.21s user 7.00s system 99% cpu 29.211 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.26s user 6.92s system 99% cpu 29.196 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.20s user 6.93s system 99% cpu 29.145 total
12
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.10s user 6.96s system 99% cpu 29.074 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.20s user 7.13s system 99% cpu 29.342 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.53s user 6.91s system 99% cpu 29.457 total
13
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.52s user 7.03s system 99% cpu 29.559 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.14s user 7.38s system 99% cpu 29.530 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.27s user 7.03s system 99% cpu 29.306 total
14
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.44s user 7.02s system 99% cpu 29.459 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.63s user 6.92s system 99% cpu 29.561 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  21.90s user 7.26s system 99% cpu 29.173 total
15
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.13s user 7.02s system 99% cpu 29.158 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.07s user 7.15s system 99% cpu 29.222 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.04s user 7.15s system 99% cpu 29.198 total
16
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.05s user 7.18s system 99% cpu 29.231 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.12s user 6.99s system 99% cpu 29.120 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  21.85s user 7.33s system 99% cpu 29.176 total
17
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.44s user 6.87s system 99% cpu 29.310 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.50s user 6.90s system 99% cpu 29.412 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.30s user 7.02s system 99% cpu 29.326 total
18
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.11s user 7.07s system 99% cpu 29.186 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.28s user 7.19s system 99% cpu 29.471 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.20s user 7.07s system 99% cpu 29.278 total
19
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.05s user 7.02s system 99% cpu 29.074 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.20s user 7.14s system 99% cpu 29.347 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.09s user 7.04s system 99% cpu 29.133 total
20
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.17s user 7.01s system 99% cpu 29.187 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  21.88s user 7.20s system 99% cpu 29.077 total
./newsboat --config-file=/dev/shm/config${i} --cache-file=/dev/shm/cache.db >  22.26s user 7.06s system 99% cpu 29.322 total
```

</details>

**Pull request merged**
