### PR TITLE
Check if generated filename is already in use when enqueueing a podcast

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes https://github.com/newsboat/newsboat/issues/1411.

There are a few things I should do before this is ready to merge:
- [x] ~Add tests (depends on https://github.com/newsboat/newsboat/issues/349, according to https://github.com/newsboat/newsboat/issues/351)~ -> Minoru might be doing this, otherwise, I can add tests in a later PR
- [x] Determine what to do if auto-enqueueing a URL fails
    - [x] Related: make sure the inline TODO is removed (remove from https://github.com/newsboat/newsboat/commit/72ab4bf88e5406d918cb02b460bb92ab08eae69c using rebase)
- [x] Include relevant information in error messages on the status line (not yet sure how to return the necessary data cleanly):
    - [x] URL on `URL_QUEUED_ALREADY`
    - [x] Generated filename on `OUTPUT_FILENAME_USED_ALREADY`
    - [x] Path to queue file on `QUEUE_FILE_OPEN_ERROR`

### CODE REVIEW

**Review by Minoru — COMMENTED** [review]
This looks good so far :+1: I'd take another look once the TODO items are resolved (I'll comment on them separately in a moment).

**Comment by Minoru** [comment]
> Add tests (depends on #349, according to #351)

Well, now that it's not *my* PR that depends on it (hehe :), I do see a way: tests should create a temporary directory and change `HOME` environment variable to point to that directory. Then `ConfigPaths` will return something like _/tmp/tmp12345678/.newsboat/queue_, and we can work with that.

I'm fine with merging this without tests because I don't require tests for modules that don't already have *some* coverage.

> Determine what to do if auto-enqueueing a URL fails 

I'd make `autoenqueue()` return `EnqueueResult`, and turn that into a message in the caller (`Controller::replace_feed()`). The only other solution I can think of is to pass `View&` into `autoenqueue()` and call `show_error()` from there, but that'd be hard to test.

> Include relevant information in error messages on the status line (not yet sure how to return the necessary data cleanly)

I faced the similar problem earlier, and the best I mustered is https://github.com/newsboat/newsboat/blob/31ae324456fa5756f33ed5f032001f5dd9559b81/include/utils.h#L139-L146

It's not very clean because `message` field can be used even if `kind` implies there is no message, and the field name is very generic. A Rust-style `enum` would be best for this, and we can get them in C++ with `std::variant`, but that one is C++17, and C++ would force us to first create separate types for all variants — I think this is too much boilerplate for too little gain.

(I also notice that I deviated from the practice of naming constants in uppercase snake-case. I'll fix it the next time I'm around that part of code :)

And finally: thank you for working on this!

**Comment by Minoru** [comment]
@dennisschagt, are you working on a test suite for `QueueManager`? I'm itching closer and closer to adding `utils::read_file_lines` to the manager, and a test suite would be a fine asset. I'm okay with waiting if you're working on it, or I can take your work and build upon it (if you have anything). I'm also okay with starting from scratch. Just let me know what your status is, so we don't end up doing the same work twice. Cheers!

**Comment by dennisschagt** [comment]
@Minoru: I had quite some distractions lately, sorry for the radio silence.

I will probably get back to this PR in a few days but, at the moment, I'm not planning to write the test suite for the `QueueManager`.
Feel free to ignore this PR for now, I will rebase it if necessary later on.
Marking as "draft" for now.

**Comment by Minoru** [comment]
Ah, okay. No problem, take your time ;) I'll work on the test suite then.

**Comment by dennisschagt** [comment]
@Minoru Thank you for the suggestions!
I think this is ready for review.

**Review by Minoru — APPROVED** [review]
Thanks! This looks good to me, merging. :+1:

**Pull request merged**
