### PR TITLE
Addresses #410 opml refactor

### PR DESCRIPTION
**Pull request by zaowen**
Move opml.cpp functionality to opmlurlreader.cpp
This PR also sets things up to make the other parts of #410 easier.

Should maintain previous functionality.

### CODE REVIEW

**Comment by zaowen** [comment]
Got it, move the importing behavior back into opml.cpp. I'll get it done

**Comment by Minoru** [comment]
Hey @zaowen, just checking—have you abandoned this, or just haven't got time to finish? No problem and no rush, just want to make sure this doesn't get too much out of date, and is still mergeable.

**Comment by zaowen** [comment]
Sorry, I became busy with school. We can close this though, since I'm redoing basically the entire PR i had planned on starting over from master and force pushing anyway.

**Comment by Minoru** [comment]
No problem! I'll close this then, and wait for your updated PR. Don't let Newsboat distract you from studies; it'll still be here when the exams are over ;) Good luck!

**Pull request closed without merging**
