### PR TITLE
Show keymap hint for "clear filter" when filter is active

### PR DESCRIPTION
**Pull request by dennisschagt**
Came up with the idea while looking into https://github.com/newsboat/newsboat/issues/2857.

This PR introduces a new translatable string so merging might need to wait until after the upcoming release.

### CODE REVIEW

**Comment by Minoru** [comment]
I like the idea!

A bit of bikeshedding: I'd prefer the "Help" hint to always come last, because it's like an ellipsis. How about putting the new hint at the very start?

**Comment by dennisschagt** [comment]
Thanks!
Rebased to make sure we get build results for FreeBSD 14.1.

> A bit of bikeshedding: I'd prefer the "Help" hint to always come last, because it's like an ellipsis. How about putting the new hint at the very start?

Nice idea, done

**Comment by dennisschagt** [comment]
In case it helps, `git -range-diff @{upstream}...` output from just before I force-pushed:
image

**Comment by dennisschagt** [comment]
I guess a similar thing can be done for tags (show `^T:Clear Tag` if a tag is selected)

**Comment by dennisschagt** [comment]
> I guess a similar thing can be done for tags (show ^T:Clear Tag if a tag is selected).
> And in help, I guess we can hide the ^F:Clear by default (and only show it after a search/highlight was executed).

Done.
For now, I've put those in separate commits to avoid a rebase.
If preferred, I'm completely fine with squashing all commits into 1.

**Pull request merged**
