### PR TITLE
Clarify how line splitting works in configs

### PR DESCRIPTION
**Pull request by Minoru**
Inspired by the discussion with allanwind starting at https://github.com/newsboat/newsboat/issues/1951#issuecomment-1358935805

### CODE REVIEW

**Review by der-lyse — APPROVED** [review]
Yeah, that's cool!

I took the liberty to rephrase a few things, so this section sound a tad nicer to my German ears. Please have a look if you like my changes. I'm not an English native speaker, so maybe somebody might tweak it even further. :-)

In any case, please squash everything in one commit before merging so we end up with a clean looking history. I only kept the commits separate to help review the changes.

**Comment by Minoru** [comment]
Thanks! I'll hold this open for one more day, maybe @allanwind will have something to say.

**Comment by allanwind** [comment]
Give me a few days.

Sep 23, 2023 20:00:55 Alexander Batischev ***@***.***>:

**Comment by Minoru** [comment]
> I would probably have phrased it as *a* long line ...

Good point, done! How does 4d0e852fbbeebaed108bd04f6787f2bfa6980ee5 look?

I also took the opportunity to replace "split" with its synonym "break" — I find that using different words make it easier for me to actually find stuff in the docs.

> most are probably familiar with backslash syntax from the shell which does strip white space.

Not inside double quotes:

```
$ cat example1.sh
#!/bin/sh

echo hello\
        dear\
             friends
$ ./example1.sh
hello dear friends
$ cat example2.sh
#!/bin/sh

echo "hello\
        dear\
             friends"
$ ./example2.sh
hello        dear             friends
```

> If you need inspiration postfix has a concept of postmap (cdb, regexp, etc) and that design has stood the test of time.

Thanks! I usually steal from Mutt, it'd be great to have some more influences.

**Comment by allanwind** [comment]
Perfect.

**Comment by Minoru** [comment]
Thank you both for the reviews and helpful comments!

**Pull request merged**
