### PR TITLE
Minor update to the Hungarian translation

### PR DESCRIPTION
**Pull request by maxigaz**
This contains translation of a confirmation message mentioned in #1932.

### CODE REVIEW

**Review by Minoru — CHANGES_REQUESTED** [review]
Thank you!

Please remove the comment saying "fuzzy": you've updated the translation and now it's correct, so it shouldn't be marked that way anymore.

Also, please update the header at the start of the file:
- `PO-Revision-Date`
- move the name from `Last-Translator` to `Language-Team`
- put yourself into the `Last-Translator` field

**Comment by Minoru** [comment]
Thanks! Please fix [this CI job](https://github.com/newsboat/newsboat/pull/1935/checks?check_run_id=4808953109) by changing the email format in `Last-Translator` field. (I would have done this myself, but for whatever reason I can't push anything to this PR.)

**Comment by Minoru** [comment]
It finally dawned at me that I tried to push my local `master` to yours, which failed since my `master` is behind yours. Fixed it now, and pushed a commit that fixes the problem I mentioned above. This PR should get merged once the CI (finally) passes.

Thanks for taking the time to update the translation, @maxigaz!

**Comment by maxigaz** [comment]
@Minoru The reason I didn't use the standard email address format (your@mail.com) is because I'm a bit concerned about spambots finding my address.

**Comment by Minoru** [comment]
Sorry, I should have asked your permission before doing that.

I'm not sure if gettext itself will complain about the email format, but our gettext linter certainly does. I guess I could change CI to ignore this particular warning on this particular line, but then I'll have to include your email in the CI config :shrug:

**Comment by maxigaz** [comment]
How about not including an email address at all? I would even go as far as not including my name either, because, for me, taking credit just for that single line is not really important.

To be clear, this isn't a huge issue for me, just a minor concern. (Also, it's already been merged, and removing it completely from history would be problematic, wouldn't it?)

**Comment by Minoru** [comment]
> Also, it's already been merged, and removing it completely from history would be problematic, wouldn't it?

Yes. The best that can be done at this point is a new commit that removes the email from the files, so: 1) scrapers have less chances of finding it; 2) the email is absent from the files in the release tarball. Also, if the bots are smart enough to pull data from Git history, they'll probably be able to pull it from the commit header too.

My email is all over this program, this repo, and the release tarballs, and I'm getting about 2 spam emails per day. I don't know how many spammers found me through GitHub, but it doesn't feel like a lot.

If you decide you don't want your email in that file after all, just send another PR that undoes the changes to headers. You may keep the comment at the top if you want. Also be warned that regardless of all that, you'll be mentioned by name in the changelog :P

**Pull request merged**
