### PR TITLE
Add Newsboat logo.

### PR DESCRIPTION
**Pull request by flexiondotorg**
This pull request adds a logo for Newsboat and a non-display desktop file to the snap. We've wanted to feature Newsboat a few times and found it lacked a logo to give the promotion some punch, so here's a logo. I hope you like it :smiley:

### CODE REVIEW

**Comment by Minoru** [comment]
Thanks! I like the image, and so do the users whom I asked on IRC. What is it's legal status, though? [Tineye found it elsewhere](https://tineye.com/search/9a1cf0c8cd78f15051b5207a2aea49ce4feab934/), including a few stock imagery sites that claim it's royalty-free.

**Comment by jaywilliams** [comment]
FYI, If the image originates from one of those stock photo websites, it can't be used for a logo unless an extended license has been purchased, and even then the logo couldn't be included under the projects MIT license.

**Comment by Minoru** [comment]
@flexiondotorg, ping.

**Comment by Minoru** [comment]
@flexiondotorg, ping.

**Comment by flexiondotorg** [comment]
Bother, looks like the image search filters for freely licensed images aren't accurate. Let's close this and I'll either make or find a suitably licensed image.

**Comment by Minoru** [comment]
Okay, cool! Thank you.

**Pull request closed without merging**
