### PR TITLE
Doc: note that FreshRSS requires Newsboat 2.24+

### PR DESCRIPTION
**Pull request by Minoru**
This addresses a question a user asked on IRC. We should do this for all
features, really. I looked through the rest of remote services we
support, and none of them are in our CHANGELOG, so I assume they were
added in Newsbeuter; thus, they were always in Newsboat.

### CODE REVIEW

**Review by der-lyse — CHANGES_REQUESTED** [review]
Looks good. According to the changelog Inoreader was added in 2.10.2 and Miniflux in 2.21. Couldn't find anything in the changelog for the other remote services, though.

People could just consult the docs of their specific version they're running, but there's certainly nothing wrong mentioning the version a feature was introduced. I just fear that this quickly gets overboard. Especially, if we want to do this also for each setting and so on.

**Comment by Minoru** [comment]
> According to the changelog Inoreader was added in 2.10.2 and Miniflux in 2.21.

Oops! Looks like I stopped at FreshRSS for some reason >_< Will fix this shortly, thanks!

> I just fear that this quickly gets overboard. Especially, if we want to do this also for each setting and so on.

I think the settings are actually the easiest case: we just add a new column to configcommands.dsv, and people fill it in when adding a new setting. Annotating all the existing settings would be a bit of pain, but it's a one-time effort.

Mentioning versions inside the text would be harder though. We managed to do it nicely [for bookmarking](https://newsboat.org/releases/2.25/docs/newsboat.html#_bookmarking), but it'd be a challenge every time I think. We'll see :)

**Comment by Minoru** [comment]
I'm on the fence about {own,next}Cloud News: support was added in 2.10, which is the first Newsboat release, so technically it was "always" in Newsboat. On the other hand, the bookmarking section refers to 2.10 even despite this. I decided not to add it here to avoid noise; but I need to think if this is a good approach overall. (I'll file an issue about this soon)

**Review by der-lyse — APPROVED** [review]
Looks good. I'd just add version 2.10 to {own,next}Cloud just for the sake of completeness. Even if that was the first Newsboat release. I reckon distinguishing between Newsbeuter and Newsboat is not that important to users in this particular case of our beloved newsreader because the transition just went so seamless if I recall correctly. :-) Either way, I'm fine with it.

**Comment by Minoru** [comment]
Okay, let's mention 2.10 then. Thanks for the review!

**Pull request merged**
