### PR TITLE
Replace Python Asciidoc with Asciidoctor

### LINKED ISSUE #645: Migrate away from AsciiDoc
Debian testing got an update to asciidoc today, and with it, this message in the changelog:

> asciidoc (8.6.10+git20190307.51d7c14-1) unstable; urgency=medium
>
>  This new version of asciidoc is using the unreleased python3 implementation
>  as python2 is deprecated. This implementation has a very low maturity to it
>  and has not seen an upstream release yet. As the maintenance of this upstream
>  is very low and they advise to use asciidoctor in the past, we advise you to
>  use asciidoctor instead as it is now the official reference for the AsciiDoc
>  language and is way ahead of this Python implementation both in terms of
>  maintenance and support of language features.
>
> -- Joseph Herlant <aerostitch@debian.org>  Sat, 07 Sep 2019 20:41:47 -0700

I've been eyeing asciidoctor for a while, but haven't tried it at all.

This might also be a good opportunity to look back at AsciiDoc and decide if it fits our purposes well, or should we be looking for another format altogether.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #645. See that issue for the rationale.

There are a lot of tiny changes, so I'll give this PR a week to gather feedback before merging.

### CODE REVIEW

**Comment by q3cpma** [comment]
Hope you'll provide an already converted manpage in the release tarballs, I'm sure I'm not the only one who doesn't want to install Ruby just for that.

**Comment by Minoru** [comment]
> Hope you'll provide an already converted manpage in the release tarballs

I didn't plan to. They're *source* tarballs after all.

How do you feel about [Pandoc](https://pandoc.org/)?

**Comment by polyzen** [comment]
Installing `pandoc` on Arch requires 59 direct dependencies (and their dependencies).

On a side, I am curious how much work it'd take to port to Sphinx after using pandoc to convert the docs to rST.

**Comment by Minoru** [comment]
I do believe that the source tarball has to contain just the source. Otherwise we might get to a dysfunctional state where the only ones who can build a certain part of the project are the maintainers, or even nobody at all. That belief applies to all the source code, not just the docs.

Now, if there is some technical argument against Asciidoc, or Ruby, or any other dependency Asciidoc pulls—let's hear it out. I'm okay with going back to the drawing board, but I need to understand *why*.

**Comment by Minoru** [comment]
Looks like I'm in a minority over this: Mcabber, Tmux, Vim, Neovim, Mutt, Neomutt, Irssi, GNU Screen, GNU Emacs all ship pre-built manpages in their source tarballs. Though to be fair, only Mcabber and Tmux actually generate them; the rest write directly in roff.

Docker CLI and Ripgrep ship source. Git ships source, but they also ship *separate* tarballs with prebuilt HTML and manpages. I don't think it makes sense for Newsboat, though, since there's only two manpages, and two HTML documents.

My "sample pool" is skewed towards older projects, but I couldn't recall any newer ones that are established enough to look up to.

Also, [this old HOWTO](https://www.tldp.org/HOWTO/Software-Release-Practice-HOWTO/documentation.html#AEN547) advises to ship both Asciidoc masters and the compiled result. The author of the HOWTO is ESR, though, and I obviously don't know enough to tell if he's making an observation about actual practice, or if he's voicing an opinion.

Still thinking.

**Comment by q3cpma** [comment]
Well, this is indeed the general practice, but Ruby is also a very heavy dependency, since it's almost never needed by other software. Especially since I think people use Newsboat in part because it's not too dependency heavy; well, now that it uses Rust, it's not a real argument, but Rust isn't that niche: stuff like rav1e is going to need it and Firefox already uses it.

Just replace "Ruby" by "Java" in the whole PR and let that sink in.

**Comment by Minoru** [comment]
> Ruby is also a very heavy dependency, since it's almost never needed by other software

That's a good point.

> Just replace "Ruby" by "Java" in the whole PR and let that sink in.

In my opinion, that's just FUD.

Thanks for the discussion. If nothing else, I'm making a more informed decision now, knowing what toes I step onto and what by-laws I break.

I still believe that source tarballs should only contain source, so that's what I'm going to continue doing.

Asciidoctor is indeed a heavier dependency than Python Asciidoc was, but we—those who write docs—will continue using it until one of us gets fed up enough to perform a migration to something else.

**Comment by q3cpma** [comment]
Have you considered https://github.com/asciidoc/asciidoc-py3/? It's packaged on
Gentoo, meaning it's probably not the shabbiest port.

**Comment by Minoru** [comment]
No, I didn't look further than Asciidoctor, because that's what the changelog entry mentioned as current de-facto standard (as quoted in #645).

Anyway, that port [is practically non-existent in distros](https://repology.org/project/asciidoc-py3/versions) compared to [Asciidoc](https://repology.org/project/asciidoc/versions) or even [Asciidoctor](https://repology.org/project/asciidoctor/versions). Not sure why Repology doesn't mention Gentoo on the first page, but that doesn't change the overall picture.

**Comment by q3cpma** [comment]
It it in Debian testing too, but yeah, the future of this port is uncertain at
the moment. Well, as long as Ruby isn't mandatory for building release
tarballs, I'm happy, personally.

**Pull request merged**
