### PR TITLE
Update .pot and .po files

### PR DESCRIPTION
**Pull request by Minoru**

### CODE REVIEW

**Comment by Minoru** [comment]
@newsboat/translators Please update your translations for Newsboat. The next release (2.23) is scheduled to happen in slightly less than two weeks, on Sunday, March 21st.

It's my bad that I didn't announce this on Sunday, so I'll wait for you a few days if you notify me that you'll be late ;)

**Comment by bitigchi** [comment]
It looks like this update marks the already-translated but not reflected help messages for deletion.

**Comment by Minoru** [comment]
Oh, looks like I forgot to update the Makefile in #1489 — thanks for spotting that @bitigchi. I haven't started on my translations yet, didn't notice this >_< I'll fix this with another PR in a moment.

**Comment by bitigchi** [comment]
Thanks for the prompt fix!

**Pull request merged**
