### PR TITLE
Remove unused includes in colormanager.cpp

### PR DESCRIPTION
**Pull request by kmws**

### CODE REVIEW

**Comment by Minoru** [comment]
Oh, and this is also blocked on #301, so you might wish to wait until that's merged before re-doing the changes here.

**Comment by kmws** [comment]
You're right, I was too eager to cut stuff off... I wouldn't want to chase all the dependencies now to be sure that I don't cut something used. I think most of the FormActions are not needed, but as I said, I'm not really sure...

I would close this one for now, maybe I will revise it in the future.

**Comment by Minoru** [comment]
Ok, no problem!

When/if you get back to it, maybe take a look at https://include-what-you-use.org/ I meant to for ages, but haven't gotten to it yet. If you turn it into a Makefile target, we can even run it on Travis ;)

**Comment by kmws** [comment]
Yep, I have heard about this tool. Will take a note of it, maybe someday... ;)

**Pull request closed without merging**
