### PR TITLE
Replaced gcov with LLVM coverage tool

### PR DESCRIPTION
**Pull request by nick-cd**
LLVM code coverage instrumentation provides Source-based coverage. Source-based coverage provides more accurate coverage data (as it [operates on AST and preprocessor information directly](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html)) at the expense of slower execution.

There is likely more work to be done before this is ready to be merged. I wanted to submit this to show my progress.

### CODE REVIEW

**Comment by Minoru** [comment]
It looks like only rust/libnewsboat/tests/utf8_to_locale_transliterates_characters_unsupported_by_the_locale_encoding.rs test ran, because the coverage for everything else is down to zero. I suspect this is related to [this note in the Rust Unstable Book](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/source-based-code-coverage.html#test-coverage):

> Since there may be more than one test binary, apply %m in the filename pattern. This generates unique names for each test binary. (Otherwise, each executed test binary would overwrite the coverage results from the previous binary.)

Can you try that please? ;)

Also curious what's up with C++. It is completely gone from the coverage report, but I don't see a reason why. Even if its coverage was overwritten by Rust, we should still see the files. Perhaps grcov's `--ignore` rules have to be adjusted somehow? I'd start by removing them and seeing what happens.

**Comment by Minoru** [comment]
Ah, awesome! Rust coverage is now [94.76%](https://coveralls.io/builds/37206558), which is close enough to [95.84%](https://coveralls.io/builds/37160446) that we have on the master branch — I'll take that!

Regarding C++: I still think it's worthwhile to fiddle with `--ignore` flags, but in addition to that — what does `--binary-path` do? Perhaps we need `--binary-path ./test/` as well? The C++ test suite is compiled to `./test/test`.

**Comment by Minoru** [comment]
I took a closer look at the reports and found a few things worth looking into:

- functions that are only tested through doctests (i.e. using a comment before the function) all have zero coverage: see [here](https://coveralls.io/builds/37206558/source?filename=rust%2Flibnewsboat%2Fsrc%2Futils.rs#L667), [here](https://coveralls.io/builds/37206558/source?filename=rust%2Flibnewsboat%2Fsrc%2Futils.rs#L177), or [here](https://coveralls.io/builds/37206558/source?filename=rust%2Flibnewsboat%2Fsrc%2Futils.rs#L73). I don't know where their binaries are put. Perhaps they're stored separately from other tests?
- there are two integration tests that didn't appear to run at all: [this one](https://coveralls.io/builds/37206558/source?filename=rust%2Flibnewsboat%2Ftests%2Fgetcwd_value_depends_on_current_directory.rs) and [this one](https://coveralls.io/builds/37206558/source?filename=rust%2Flibnewsboat%2Ftests%2Fgetcwd_returns_an_error_if_current_directory_doesnt_exist.rs).

**Comment by Minoru** [comment]
Hey @nick-cd, how it's going? :wave: Not trying to hurry you up, just checking in to see if there's something I can do to help here.

**Comment by nick-cd** [comment]
Hey sorry again for the silence. I've just been backed up with school work (midterm week for me :worried:) and haven't been working on this as much. But I believe I had some luck in pinpointing the issue.

Regarding the rust integration tests, the tests themselves are not actually being ignored, rather LLVM runs into an [issue creating the profraw file](https://github.com/newsboat/newsboat/runs/1919799194#step:9:908) for those tests specifically. After looking into it for some time I believe I understand the underlying problem. 

LLVM creates a new profraw file after every test in the *current working directory*. In these tests, we change the current working directory to a *short-lived temporary directory*. After the test is complete, the current working directory *is a non-existent directory*. Since that directory is non-existent, when the test completes and LLVM creates the profraw file, the operation fails. It's  a slippery slope from here. `grcov` does not see that the file was indeed covered in our tests inadvertently causing coveralls to seemingly neglect the inclusion of this information.

**Comment by Minoru** [comment]
> I've just been backed up with school work (midterm week for me :worried:)

Please don't get kicked out of school because of Newsboat! :)

> LLVM creates a new profraw file after every test in the current working directory. In these tests, we change the current working directory to a short-lived temporary directory. After the test is complete, the current working directory is a non-existent directory. Since that directory is non-existent, when LLVM creates the profraw file, the operation fails.

Ah! Makes sense. I guess we didn't have this problem with our previous code-coverage approach because it opened the profraw file *before* running the tests?

I think we should change those tests to follow the same approach as our C++ tests follow: create a temporary object that chdirs into the temporary directory, and when that object is automatically dropped at the end of the test, it should chdir back into the original directory. C++ tests do this because they all run in a single process, and so each test takes care to preserve the environment. Rust tests don't do this because: 1) the ones in `mod tests` are unit-tests which don't change the environment; 2) the ones in _tests/_ subdirectories contain one test per executable, so there is no point restoring the environment — it's going to be torn down shortly when the executable finishes running. Now it makes sense to do in Rust what we do in C++.

The relevant C++ helpers are [here](https://github.com/newsboat/newsboat/blob/master/test/test-helpers/chdir.h) and [here](https://github.com/newsboat/newsboat/blob/master/test/test-helpers/chdir.cpp). Should be easy enough to write similar ones in Rust and use them in integration tests; I can do that for you if you aren't interested.

I'll make sure not to bother you about this PR for at least a couple weeks, you've got your hands full already. Best of luck with your mid-term!

**Comment by Minoru** [comment]
JFYI, I think you must rebase onto master to pull in https://github.com/newsboat/newsboat/pull/1511, otherwise the Coveralls job will install a newer Rust Nightlly and C++ tests will segfault.

**Comment by Minoru** [comment]
@nick-cd, so what's the status of this? Looks like the Rust coverage works fine, and the only remaining problem is to get C++ coverage back?

Not trying to hurry you up; just want to see if you need someone to brainstorm solutions with, or something like that.

**Comment by nick-cd** [comment]
Hey, I have just been stuck on this issue.

The rust tests aren't exactly complete. If you take a look at the [coverage of my last commit](https://coveralls.io/builds/38403846/source?filename=rust%2Flibnewsboat%2Ftests%2Fgetcwd_value_depends_on_current_directory.rs#L21), the last line is simply not included in the test coverage. I been thinking about this problem for quite some time and I still have no coherent explanation as to why that line is skipped.

For C++, I had forgotten to respond to your suggestions/questions: 

> Regarding C++: I still think it's worthwhile to fiddle with --ignore flags

Unfortunately, I had no luck with trying this. Removing --ignore flags seemingly had no effect on the output. 
At one point, I had attempted to move to contents of the `./test/test` into `./target/debug/deps/` — no luck with that either.

> what does `--binary-path` do?

the --binary-path is [required](https://github.com/mozilla/grcov#generate-a-coverage-report-from-coverage-artifacts) to instruct `grcov` to do source-based coverage

> Perhaps we need `--binary-path ./test/` as well? The C++ test suite is compiled to `./test/test`.

`grcov` forbids mentioning the `--binary-path` option more than once. I recall attempting to do this and `grcov` exited with an error.

I've been trying to research more about `grcov` and see what other people have done in other projects. However, all of them seem to do source-based coverage on exclusively rust code. There were no projects (at least from what I found) using `grcov` on a hybrid project similar to Newsboat. 

So I'm stumped. I'm not sure how to proceed with this task.

**Comment by Minoru** [comment]
> If you take a look at the coverage of my last commit, the last line is simply not included in the test coverage.

Hmm, it shows no source at all:

Screenshot_2021-04-10 Coveralls io - Test Coverage History and Statistics

Yet [the last build of this PR](https://coveralls.io/builds/38403775) does have the source code, and I do [see the problem there](https://coveralls.io/builds/38403775/source?filename=rust%2Flibnewsboat%2Ftests%2Fgetcwd_value_depends_on_current_directory.rs). It's puzzling, but it's obvious from the code that this line *was* executed if a test passed; so I'm not worried about this at all.

> I had attempted to move to contents of the ./test/test into ./target/debug/deps/ — no luck with that either.

Perhaps *.profraw files have to be reside next to the binary, i.e. they should be moved too?

Alternative approach: abandon Rust tests for now, and target grcov at C++ tests. Make sure that works. Then think how to unify the two :) We could, for example, invoke `grcov` twice to collect Rust and C++ coverage separately into two different lcov files, then use `lcov` to merge them, and that's what will be submitted to Coveralls. Maybe coverallsapp/github-action will do the merge for us if it finds multiple lcov files, I don't know. (In fact, this approach should be more robust than moving test binaries and profraw files around.)

Thanks for the ton of work you did here already! Don't hesitate to drop this if you've lost interest, though; it'd be a pity but it's not worth burning yourself out over this ;)

**Comment by nick-cd** [comment]
> Thanks for the ton of work you did here already! Don't hesitate to drop this if you've lost interest, though; it'd be a pity but it's not worth burning yourself out over this ;)

Thanks for the kind words! 

Unfortunately, I think I have to drop this. This task is much more challenging (at least for me) than I originally anticipated. Sorry to disappoint.

**Comment by Minoru** [comment]
You didn't disappoint at all! The task is indeed thornier than anticipated. Despite that, you worked out all the kinks in Rust coverage, that's half the task already. I'm pretty sure that the remaining problems with C++ will be easier to solve thanks to all the things you tried and discovered while working on the Rust part. And I'm pretty sure your changes will be the base for the PR that finally resolves this, so you'll also get credit for all that you've done here ;)

**Pull request closed without merging**
