### PR TITLE
Skip query feeds when processing `-x print-unread`

### LINKED ISSUE #1120: Option to not double count articles because they're in query feeds
When I run `newsboat -x print-unread`, it counts all the new articles, and all the new articles in query feeds. The problem arises when I *exclusively* use query feeds, and the status bar script I wrote doesn't accurately portray how many new articles I have, because it counts articles more than once.

If there's a purpose to this, I would be glad to know, and perhaps there could be another command that only counts once.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #1120.

Reviews are welcome! I'll merge this in three days if no issues are raised.

### CODE REVIEW

**Comment by polyzen** [comment]
I wasn't using `prepopulate-query-feeds yes`, but this fixed my issue with the `"query:Unread Articles:unread = \"yes\""` article count being shown with `notify-format "%d new article(s)"` (which led to new articles being counted twice).

**Comment by Minoru** [comment]
@polyzen Oh, thanks for reminding me about that, I totally forgot! I need to re-think this PR in light of https://github.com/newsboat/newsboat/issues/444#issuecomment-462923072.

**Comment by Minoru** [comment]
Also, builds failed because of how Cirrus handles caches: when it fails to unpack it, it removes the "cache folder" and tries again. This also removes ~/.cargo/bin which breaks the build. I'll look into that as well.

**Comment by Minoru** [comment]
Superseded by #1140. @polyzen, can you please check that the new PR still works for you?

**Pull request closed without merging**
