### PR TITLE
Introduce new-ish code style, along with rudimentary style guide

### PR DESCRIPTION
**Pull request by Minoru**
In #28, @noctux mentioned a code style guide, and maybe some automatic checks or even formatting. Well, here goes.

After looking at [Google's C++ Style Guide](https://google.github.io/styleguide/cppguide.html), I was instantly sold on the idea of automatic formatting. No-one, including me, is going to read a document like that just to contribute a patch to Newsboat :)

As mentioned in #28, we already employed `astyle` for formatting, but simple comparison showed that `clang-format` is much more configurable, so I made the switch. Still, `clang-format` couldn't preserve a lot of our code as-is. I'm not sure if it's a bad thing given it's a one-time conversion. I'm interested in your thoughts on this.

I found that our use of tabs really constrain us in the kind of alignment we can do (doh!). See below for interesting consequence it had on member initializers in constructors.

Decisions I'd like to highlight:
- curly braces with function bodies always go on separate lines. I used to be on the fence about this, because it wastes a line when function name is short, but names of our test cases are always long, and consistent style is more important than always-beautiful style;
- queer way for aligning member initializers in constructors. Just [take a look](https://github.com/newsboat/newsboat/blob/86767c6e7ee366404e5c5c5d3e169b48b14132f9/include/configcontainer.h#L17);
- asterisks in pointers are grouped to the left ("const char* str"). I know it's not how compiler sees it, but grouping to the left [seem to be the preferred approach in C++](https://isocpp.org/wiki/faq/style-and-techniques#whitespace). We don't use that many pointers anyway, and for references, grepping shows that '[^&]&\s' occurs 1038 times, whereas '\s&[^&]' occurs only 322 times; the latter matched a lot of lines where we take a pointer of something, too;
- includes are now separated into a few groups, and `clang-format` will keep each group sorted. Grouping is described in the Code Style Guide; hope my rationale is strong enough.

Things I had to let go of:
- space after `!` in `if`s. `clang-format` removes the space.

The style guide is rudimentary at the moment, but I think we'll add new items there as we bump into problems.

@tsipinakis, @noctux, @der-lyse, what do you guys think? Is there something about the new style that you absolutely hate, or think a mistake?

I also welcome opinions by anyone else who ever contributed code to Newsboat or Newsbeuter.

There's absolutely no deadline on this, because these changes can't get out of sync, but I'll merge them 7 days after last comment here.

### CODE REVIEW

**Comment by noctux** [comment]
Hey, thank you for the work and the thought you've put into it!

I think I'll have to take a closer at the code for a more thorough opinion. However, just a quick sidenote on the usage of tabs:

> I found that our use of tabs really constrain us in the kind of alignment we can do (doh!). See below for interesting consequence it had on member initializers in constructors.

There are several projects with the following rule (sometimes refered to as "smart tabs"): Use tabs for indentation and spaces for alignment.

I've always been rather content with that rule: Indentation (and its width) are something quite personal, some people prefer it to be minimal, e.g. 2 spaces, other like it to be 8 spaces because a tab ought to have 8 spaces etc.pp.. Keeping indentation to tabs means that everyone can tune that setting to her likening in the editorconfig, while all alignment (e.g. function parameters, multiline conditionals, etc.) still looks consistent and pretty.
For `clang-format`, a `UseTabSytle = ForIndentation` might to the trick to some extend.

**Comment by der-lyse** [comment]
I'm by no means a *C++* programmer, but here are my two cents:

> No-one, including me, is going to read a document like that just to contribute a patch to Newsboat :)

You're absolutely right, neither did I! I just scrolled over it. It's simply waaaaaaay too much.

In my opinion automatic code formatting is a usually good thing. One could think about providing a commit hook that people can install in order to reject ill-formatted code patches right away. However, I'm not sure if it is possible, that only the touched lines are checked/rejected. And yes, not everybody will install the hook.

Also when having an auto formatter I sometimes disable it for a small code segment, because I want to align the code differently, e.g. having a nicely formatted table layout sometimes is more readable. This only occurs rarely, but every now and then it's nice to be able to do that (shooting from the hip, this happens especially in tests). I'm not sure whether this is useful for Newsboat or not, I don't know the code base well enough.

> space after `!` in `if`s. `clang-format` removes the space.

I personally like that. ;-)

Regarding the mix of tabs and spaces: I think this a bad thing and one should only use either or to indent and align. Judging from my experience, mixing caused all sorts of trouble with misaligned code. But I never used EditorConfig, so the mix of tabs and spaces may be not that worse anymore. Looking back I switched from tabs to spaces and back quite a number of times, currently I'm sold on 4 spaces. But that's maybe the Python coder in me.

**Comment by Minoru** [comment]
@noctux, sorry, I keep postponing an answer to you because I want to play with mix of tabs and spaces first, but haven't got around to it yet. Hopefully on weekend (but don't I always say that?).

@der-lyse, I like the commit hook idea. Maybe we should run `clang-format` as Travis job as well, to catch those who don't run `make fmt` before comitting :)

`clang-format` allows disabling formatting for a specific line by placing a comment on it, but I'll have to dig further to find out if one can disable auto-formatting for a whole region of the code. Escape hatches are important to have even if we never use them.

**Comment by Minoru** [comment]
Turns out clang-format already mixes tabs with spaces in situations like this:

```c++
auto x = do_work(long_argument_1,
                 another_long_argument,
                 even_longer_argument_that_certainly_won_t_fit_with_the_rest);
```

and this:

```c++
auto y = 1
         + a_very_long_line_that_can_t_fit_on_the_previous_one;
```

In both cases, it relies on tab occupying 8 spaces (the width is configured by me). But if I configure my editor to display 4 spaces for each tab, the code looks ugly:

```c++
auto x = do_work(long_argument_1,
         another_long_argument,
         even_longer_argument_that_certainly_won_t_fit_with_the_rest);

auto y = 1
     + a_very_long_line_that_can_t_fit_on_the_previous_one;
```

I'd rather it used only tabs, and looked pretty much the same regardless of tab width:

```c++
auto x = do_work(
        long_argument_1,
        another_long_argument,
        even_longer_argument_that_certainly_won_t_fit_with_the_rest);

auto y =
        1
        + a_very_long_line_that_can_t_fit_on_the_previous_one;
```

But I can't make clang-format do what I want! First of all, it seem to ignore `AlignAfterOpenBracket`: even though I set it to `AlwaysBreak`, it still leaves the first argument on the same line as the function name. Second, I can't make it put "1" on a separate line: since it's short, clang-format keeps it on the same line as assignment operator. Does anyone have relevant experience and can help?

**Comment by Minoru** [comment]
I kept postponing the merge because I wanted to make another pass over the results, but this just isn't happening. I have just rebased commits onto master, and will merge them once Travis build is done. Later on, if anyone runs into an issue with formatting, just open an issue and we'll see what to do about it.

**Pull request merged**
