### PR TITLE
Rustify utils::remove_soft_hyphen

### PR DESCRIPTION
**Pull request by rnestler**

### CODE REVIEW

**Comment by rnestler** [comment]
> Looks great, will merge once the checks are green +1 Thanks for the work!

The problem is, that the [`retain`](https://doc.rust-lang.org/std/string/struct.String.html#method.retain) method got only added in Rust 1.26.0, so it is not available on Rust 1.25.0.
Should I work around it or would it be OK to bump the minimal required Rust version for this?

**Comment by Minoru** [comment]
Let's just copy the implementation of retail from std—it's dual-licensed under Apache 2.0 and MIT, so it's compatible. You can open an issue to replace it with an actual thing when we're on 1.26+, and mention that in a TODO near the callsite.

I'm lazily researching approaches to Rust compatibility, and don't want to change anything without prior notice to downstream maintainers.

**Comment by rnestler** [comment]
> I'm lazily researching approaches to Rust compatibility, and don't want to change anything without prior notice to downstream maintainers.

FWIW I took a look at distros packaged Rust versions:
 - [Debian Stretch: 1.24.0](https://packages.debian.org/search?suite=stretch&searchon=names&keywords=rustc)
 - [Debian Buster: 1.34.2](https://packages.debian.org/search?suite=buster&searchon=names&keywords=rustc)
 - [Ubuntu 16.04: 1.34.1](https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=rustc)
 - [Ubuntu 18.04: 1.34.1](https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=rustc) This one is a bit weird because there seems to be only Rust 1.24.1 for ARM architectures.
 - CentOS 7: 1.35.0 according to https://pkgs.org/download/rustc which I'm not sure if it is official

So 1.34 would look like a good baseline to be build-able on mainstream Linux distros. You could also take a look at https://wiki.mozilla.org/Rust_Update_Policy_for_Firefox, but it doesn't look that up to date.

**Comment by rnestler** [comment]
> Let's just copy the implementation of retail from std—it's dual-licensed under Apache 2.0 and MIT, so it's compatible. You can open an issue to replace it with an actual thing when we're on 1.26+, and mention that in a TODO near the callsite.

I'm not sure if we really wanna do that if I look at the implementation :wink: also it of course accesses private members of the string, so would be difficult to achieve anyway.
```Rust
    pub fn retain<F>(&mut self, mut f: F)
        where F: FnMut(char) -> bool
    {
        let len = self.len();
        let mut del_bytes = 0;
        let mut idx = 0;

        while idx < len {
            let ch = unsafe {
                self.get_unchecked(idx..len).chars().next().unwrap()
            };
            let ch_len = ch.len_utf8();

            if !f(ch) {
                del_bytes += ch_len;
            } else if del_bytes > 0 {
                unsafe {
                    ptr::copy(self.vec.as_ptr().add(idx),
                              self.vec.as_mut_ptr().add(idx - del_bytes),
                              ch_len);
                }
            }

            // Point idx to the next char
            idx += ch_len;
        }

        if del_bytes > 0 {
            unsafe { self.vec.set_len(len - del_bytes); }
        }
    }
```
I think we can just use a `String::replace` for now and live with the inefficiency due to the extra allocation.

**Comment by Minoru** [comment]
Regarding Rust 1.34 as a baseline: yeah, I've been using [this Repology page](https://repology.org/project/rust/versions), and it seems that latest-2 is where most distros are. I wanted to research how other Rust applications handle their minimum requirement, but haven't gotten around to that yet. My current idea is after every Newsboat release, bump the minimum to latest_stable-2, update Cargo.lock, do refactors, and spend the next three months sitting on that version. This means that:
* we're never "too new", always supporting the last three releases;
* when we release, we support the last 5 Rust releases (our cycle is 3 months or 12 weeks, Rust cycle is six weeks).

Re copying `retain`: agreed, the idea wasn't too good :) I'm happy with what you've done instead. Thank you very much for working on this!

**Comment by Minoru** [comment]
Just realized: Rust tests are missing :) Same for #575. I can add them myself unless you want to, @rnestler?

**Comment by rnestler** [comment]
> Just realized: Rust tests are missing :) Same for #575. I can add them myself unless you want to, @rnestler?

I can add them, but I probably won't find time for it in the next few weeks. Can you ping me in 2-3 weeks?

**Comment by Minoru** [comment]
I'll add them myself, then, just to call this finished.

**Pull request merged**
