### PR TITLE
Add "hints" field to avoid crash when swapping title with hints

### PR DESCRIPTION
**Pull request by dennisschagt**
Fixes https://github.com/newsboat/newsboat/issues/1399.

I want to check a bit more thoroughly if we have any similar interactions with STFL which could be broken.
I plan to do that later today.

- [x] Check for similar issues with STFL interaction

### CODE REVIEW

**Review by Minoru — APPROVED** [review]
This looks good to me, thanks for the PR!

I `diff`ed all the STFL files to see what other parts they all have in common. Some define the `hints` thing as `hbox` rather than `vbox`, but this shouldn't be a problem. All STFL files have sub-element `label#info` under `hints`, which is touched by `ColorManager` when processing `color info X Y Z`. However, I wasn't able to make Newsboat crash by defining a new style for "info", so we probably don't need `label#info` in the empty formaction. The `label#info` thing contains `text[help]` which is set from `FormAction` class but doesn't crash anything yet, so I don't think it's important either.

**Comment by Minoru** [comment]
I didn't merge this myself because you wanted to do some more checks. Feel free to merge once you're done with that.

**Comment by dennisschagt** [comment]
Thank you for the review and the extra checks!

**Comment by Minoru** [comment]
Marking for 2.22.1 release because this is a regression in 2.22.

**Pull request merged**
