### PR TITLE
Escape URLs for Inoreader, Old Reader

### LINKED ISSUE #175: Failed to sync with inoreader for youtube rss
**Newsboat version (copy from `newsboat -v`)**: 2.11

As title suggests, every other feeds from the same inoreader account are retrieved but not the youtube related one. 

It responded with the code below:
Error while retrieving https://inoreader.com/reader/atom/feed/https%3A//www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA?n=120: HTTP response code said error 400

### PR DESCRIPTION
**Pull request by erikli**
Resolves #175 , #188 for inoreader and old reader

It's been a while since I've done any C++ coding (read: over a decade) and I'm not a programmer by trade, but it seemed like a simple enough change

### CODE REVIEW

**Comment by erikli** [comment]
The other thing to think about would be the inoreader API usage issue. It looks like Zone 1 is 5000 requests per day according to https://www.inoreader.com/developers/rate-limiting and that will quickly saturate if even a few users are using this with say ~30 feeds and a reasonable polling schedule. Say 30 feeds, poll every hour, 12 hours a day --> 5000/(30*12) = ~13 reasonable users with more than a few feeds will kill Inoreader sync via newsboat.

I don't know if the inoreader license permits each user setting up an API key but if so that may be the much better way to go. It seems like it was discussed a bit in #22 but I don't know how hard it would be to implement.

**Comment by Minoru** [comment]
Looks good to me, thank you very much! I'm waiting for the Travis build to pass before I can merge this.

I'm surprised this fixes #186. Are you totally sure it doesn't work without this change, but works with it?

Re API usage issue: indeed, we recently hit a limit even though just 2 users were active at the time (see #285). I'm still monitoring to see if it was a fluke, or we're really overreaching the quota. I think API keys are supposed to be per-app, not per-user, and we (as a project) should simply request a limit increase if we get enough users.

It's quote possible to add settings for this; you'll have to modify `configcontainer`, document them in doc/configcommands.dsv, and use the settings instead of `INOREADER_APP_ID` and `INOREADER_APP_KEY`.

**Comment by Minoru** [comment]
Thank you for the contribution, @erikli! I'll close #188 if you can confirm that this PR indeed fixed it.

**Comment by erikli** [comment]
@Minoru You are totally right! I was scanning the issues quickly and misunderstood the problem with #188.  This PR does not fix #188.

Query Feeds are not a part of my setup so I mixed up "Query Feeds" and "HTTP Query Strings". Interestingly in playing with this feature I see that you can put a query feed into `$HOME/.newsboat/urls` with an inoreader setup and it will show up in the feed list, but you cannot combine that with direct feed urls in `$HOME/.newsboat/urls`

I'll edit my initial comment above so it doesn't confuse people. Thanks!

**Pull request merged**
