### PR TITLE
Clarify what dir has to exist for Newsboat to use XDG

### LINKED ISSUE #1706: Newsboat doesn't read $XDG_CONFIG_HOME unless a newsboat folder exists inside it
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: Newsboat 2.24.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
None
```

Steps to reproduce the issue:

1. Set $XDG_CONFIG_HOME to a directory in your home directly that exists and is readable and writable by you (preferably the .config directory in your home directory)

2. Make sure the env is readable in the terminal your are going to execute `newsboat` AND a folder `newsboat` does NOT exist in $XDG_CONFIG_HOME AND that there is no urls file under ~/.newsboat/

3. Execute `newsboat`

I am opening an issue instead of a PR as I believe it's not the documentation that's wrong but newsboat. What the documentation says, that if $XDG_CONFIG_HOME exists, newsboat will make its own folder there, I believe should be the actual behavior.

### PR DESCRIPTION
**Pull request by Minoru**
Fixes #1706.

@ifohancroft, can you please take a look at this? Is this any clearer than before? I suspect I might still not be explaining it too well.

### CODE REVIEW

**Comment by ifohancroft** [comment]
That's almost perfect!

I'd change it even further, to say something like: If `newsboat` folder exists, under $XDG_CONFIG_HOME, newsboat will use that location, otherwise it would default to ....

**Comment by Minoru** [comment]
Like this?

**Comment by ifohancroft** [comment]
> You mean, something like this?

Yes. It seems perfect to me!

Btw what happens if $XDG_CONFIG_HOME/newsboat/ exists, but $XDG_DATA_HOME/newsboat doesn't and you start newsboat?

**Comment by Minoru** [comment]
The data dir will be created by Newsboat. Actually, I should add that to the doc as well…

**Review by ifohancroft — APPROVED** [review]
Ooh! That's even better.

**Comment by Minoru** [comment]
@ifohancroft Thanks!

@der-lyse, once you've taken a look, and if you're satisfied — please squash and merge this.

**Review by der-lyse — APPROVED** [review]
Very nice, this looks great! I just added an article, please check!

**Review by ifohancroft — APPROVED** [review]

**Comment by Minoru** [comment]
Ah, articles, the bane of my English writing. Thanks @der-lyse! I'll enable auto-merge here then.

**Pull request merged**
