### PR TITLE
Move bookmark() to formaction.cpp, as it is only used there

### PR DESCRIPTION
**Pull request by kmws**

### CODE REVIEW

**Comment by Minoru** [comment]
Don't believe anything Coveralls says—I just canceled the previous Travis build to speed up the new one.

**Comment by kmws** [comment]
I was not intending to push `8f61r74` and `9761a26` commits here... my bad. If they are acceptable here, feel free to merge them. If they're not, I will happily open another PR and/or modify them.

**Comment by Minoru** [comment]
It's all right. I'm going offline now and Travis haven't finished yet, so I'll merge in the evening tomorrow.

(You can use that delay to change "SIGINt" to "SIGINT" :P)

**Comment by Minoru** [comment]
The typo doesn't matter, so I merged as-is. Thank you, @kmws!

**Pull request merged**
