### PR TITLE
Fix -Wpedantic warnings

### PR DESCRIPTION
**Pull request by Minoru**
This is yet another follow-up to https://github.com/newsboat/newsboat/pull/2654. The idea is: since we declare that C++11 compiler is enough for us, we should check that. We already checked by compiling with old compilers that didn't support newer standards, but that still left some room for error: e.g. GCC and Clang are fine with using designated initializers for structures even though they only appeared in C++20.

### CODE REVIEW

**Comment by Minoru** [comment]
The code produced by `cxx` crate doesn't build with `-Wpedantic`: https://cirrus-ci.com/task/6117236939685888 I really don't want to put in kludges to work around that :( Perhaps I could persuade cxx' authors to change their code generator a little bit? I'll ponder.

Ideas welcome :)

**Comment by Minoru** [comment]
There's an issue for that, albeit with no response from the maintainer: https://github.com/dtolnay/cxx/issues/722

**Review by dennisschagt — APPROVED** [review]
Looks good

On a related note, do you want to update the compiler flag to c++14 / c++17 at some point?
If yes, is there anything in particular you want to see in gcc/clang linux/macos availability?

If I'm not mistaken, our minimum supported compiler versions (GCC 5, Clang++ 4) already support the full specification of c++14:
- https://gcc.gnu.org/projects/cxx-status.html#cxx14
- https://clang.llvm.org/cxx_status.html#cxx14

(our readme specifies clang 3.6 but it looks like we test with clang 4 and up)

**Comment by Minoru** [comment]
Oh, I didn't realize we could jump to C++14 without bumping the minimum requirements! This is great news, because Catch2 (in their 3.x branch) now uses C++14. I'll make a PR in a second, and if nothing fails, let's switch to C++14 starting with this upcoming release.

As for C++17, I don't have a specific set of requirements. Before the Rust port, I was thinking along the lines of "upgrading a compiler is hard, so let's see what we can achieve with C++11 alone". After the Rust port started, my thinking switched to "we can probably stay at C++11 until we've ported all the code to Rust".

C++ is not Rust; I won't upgrade just for the sake of upgrading. Is there anything specific you'd like to try from C++17/20/23? The only things that come to my mind are `std::make_unique` (C++14) and template lambdas (they became fully functional in C++17, I believe), but aside from that, I don't have a strong urge to upgrade.

**Comment by Minoru** [comment]
PR delayed because I attempted to migrate to `std::make_unique` and ran into some problems with arrays in `test_helpers::Opts`. I'll solve those tomorrow.

**Comment by dennisschagt** [comment]
> C++ is not Rust; I won't upgrade just for the sake of upgrading. Is there anything specific you'd like to try from C++17/20/23?

There is nothing big coming to mind, but I do have a few small features which I accidentally used before (and had to revert due to failing CI):
- [Designated initializers](https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers) (c++20)
- [[nodiscard]](https://en.cppreference.com/w/cpp/language/attributes/nodiscard) (c++17)

There are a few additions which I was looking forward to, but which I think are not really necessary anymore for Newsboat:
- [filesystem](https://en.cppreference.com/w/cpp/header/filesystem) -> I guess we moved most (or all) of our file handling to Rust
- [optional](https://en.cppreference.com/w/cpp/header/optional) -> We already have optional-lite as an alternative

So I don't have strong reasons for updating to a newer c++ standard, but it can still be nice when it can be done without impact on users (like now with the c++14 update)

**Comment by Minoru** [comment]
I'm merging this without adding the CI check. It's not my preferred way of doing things, because it's easy to re-introduce `-Wpedantic` violations, but it's better than not merging these changes at all. Hopefully someday cxx gets fixed (perhaps by me!) and we can update our CI then.

**Comment by Minoru** [comment]
Merging manually because since this PR was made, we migrated FreeBSD from 13.2 to 13.3 and added 14.0; both checks are now required, but they didn't run for this PR, so this PR can't be auto-merged.

**Pull request merged**
