### PR TITLE
Document how to get articles from hidden feeds

### PR DESCRIPTION
**Pull request by Minoru**
Cf. #33. It doesn't fix the issue, but it at least explains the
workaround.

### CODE REVIEW

**Comment by allanwind** [comment]
The double "hidden" is confusing, and at first glance I would wonder if the second "hidden" is a keyword.  It's also odd that the descriptive tag is the one that you cannot query on.  I suggest you leave "!" stand-alone as you cannot query on the associated tag anyways, but then introduce a 2nd feed so you two are tagged and then query on the descriptive tag name:

http://feeds.bbci.co.uk/news/world/rss.xml ! "News"
https://rss.orf.at/news.xml ! "News"
"query:World News:tags # \"News\""

**Comment by Minoru** [comment]
Yeah, makes sense. I updated the doc, can you please take another look?

(Also fixed the indentation of the example code; turns out I should use tabs not spaces!)

**Comment by allanwind** [comment]
The first feed you use the tag ! and the 2nd one you use !hide.  I would make them both a bare ! (just so user doesn't get the idea that they can query on the tag hide) but I suggest they are consistent.

**Review by der-lyse — APPROVED** [review]
Yep, looks good to me!

**Comment by Minoru** [comment]
I did that intentionally, so the user doesn't get the idea that "!" is the only possible "hidden" tag. Although with #500 in mind, perhaps I *should* promote "!" instead of any other variant. Since Lyse upvoted that comment, I am in the minority so I'll update the PR once again :)

**Comment by der-lyse** [comment]
Reading the comments, I second @allanwind's opinion on the `!hide` part.

**Comment by Minoru** [comment]
Okay, here's one more update. I also added an explanation why "hidden" tags don't have names per se. Does it make sense?

**Review by der-lyse — APPROVED** [review]
Yes, that's indeed the best description in my opinion (but I don't actually use tags, so I might overlook something).

**Comment by Minoru** [comment]
Okay, let's merge it then. Thank you both for the review!

**Comment by Minoru** [comment]
Oops, forgot to squash the fixups :( I'll learn to remember, any day now.

**Pull request merged**
